config/routes.rb
Mbatechcrashcourse::Application.routes.draw do

  get "courses/VIP" => "content#VIP", :as => :content_VIP
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users
  root "pages#home"
  get "about" => "pages#about"
  get "comments" => "pages#comments"
  get "courses" => "pages#courses"
  get "testcourse" => "pages#testcourse"
  get "administration" => "pages#administration"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :view, :VIP if user.has_role? :VIP
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :stripe_token, :coupon
  attr_accessor :stripe_token, :coupon
  before_save :update_stripe

  def update_stripe
    return if email.include?(ENV['ADMIN_EMAIL'])
    return if email.include?('@example.com') and not Rails.env.production?
    if customer_id.nil?
      if !stripe_token.present?
        raise "Stripe token not present. Can't create account."
      end
      if coupon.blank?
        customer = Stripe::Customer.create(
          :email => email,
          :description => name,
          :card => stripe_token,
          :plan => roles.first.name
        )
      else
        customer = Stripe::Customer.create(
          :email => email,
          :description => name,
          :card => stripe_token,
          :plan => roles.first.name,
          :coupon => coupon
        )
      end
    else
      customer = Stripe::Customer.retrieve(customer_id)
      if stripe_token.present?
        customer.card = stripe_token
      end
      customer.email = email
      customer.description = name
      customer.save
    end
    self.last_4_digits = customer.cards.data.first["last4"]
    self.customer_id = customer.id
    self.stripe_token = nil
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "#{e.message}."
    self.stripe_token = nil
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
  		courses_path
	end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  before_filter :authenticate_user!

  def VIP
  	authorize! :view, :VIP, :message => 'Access limited to VIP subscribers.'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end

  def courses
  end

  def comments
  end

  def testcourse
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def new
    @plan = params[:plan]
    if @plan && ENV["ROLES"].include?(@plan) && @plan != "admin"
      super
    else
      redirect_to root_path, :notice => 'Please select a subscription plan below.'
    end
  end

  private
  def build_resource(*args)
    super
    if params[:plan]
      resource.add_role(params[:plan])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/content/VIP.html.erb
<h1>Content#VIP</h1>
<p>Find me in app/views/content/VIP.html.erb</p>

app/views/layouts/_footer.html.erb
<section class="first-footer">
    <div class="container">
      <div class="row center" style="margin-top:100px;margin-bottom:100px;">
        <div class="col-md-6" style="text-align:left">
          <h2>Questions?  Contact us:</h2>
          <p>techmba@gmail.com</p>
          <div class="social-media">
            <%= link_to image_tag("twitter-icon.png", :alt => "twitter-icon"), "http://www.medpreps.com" %>
            <%= image_tag("facebook-icon.png", :alt => "facebook-icon") %>
            <%= image_tag("googleplus-icon.png", :alt => "google-plus-icon") %>
            <%= image_tag("linkedin-icon.png", :alt => "linkedin-icon") %>
          </div>

        </div>
        <div class="col-md-6" style="text-align:right;">
          <%= link_to "FAQ", "#" %><br>
          <%= link_to "FAQ", "#" %><br>
          <%= link_to "FAQ", "#" %><br>
        </div>
      </div>
    </div>
</section>

<footer class="footer">
    <div class="container">
      <p>TechMBA &copy; 2013</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
	<div class="container"
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <%= link_to "Tech MBA", root_path, class:"navbar-brand" %>
	  </div>

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse navbar-ex1-collapse">
	    <ul class="nav navbar-nav navbar-right">

        		<% if user_signed_in? %>
        		   <% if current_user.has_role? :admin %>
				      <li>
				      <%= link_to('Admin', users_path) %>
				      </li>
				   <% end %>
        		  <li><%= link_to "Courses", courses_path %></li>
        		  <li><%= link_to "Q&A", comments_path %></li>
        		  <li><%= link_to "Account Settings", edit_user_registration_path %></li>
		          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
		        <% else %>
        		  <li><%= link_to "About", about_path %></li>
		          <li><%= link_to "Sign in", new_user_session_path %></li>

		          <li><%= link_to "Enroll today for $20", new_user_registration_path(:plan => 'VIP') %></li>

		        <% end %>
    </ul>
	  </div><!-- /.navbar-collapse -->
	</div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mbatechcrashcourse</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
	<%= render 'layouts/header' %>
		<% flash.each do |name, msg| %>
    		<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>

  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<h1>About us</h1>
	<p>Elliot and Kenny</p>
</div>

app/views/pages/administration.html.erb
<h3>Administration</h3>
<% @users.each do |user| %>
  <p>User: <%= user.name %> </p>
<% end %>

app/views/pages/comments.html.erb
<div class="container">
	<h1>Comments</h1>
	<p>Example of comments here</p>
</div>

app/views/pages/courses.html.erb
<div class="container" style="padding-bottom:500px;">
	<h1>Courses</h1>
	<h3>Course header 1</h3>
	<a class="list-group-item" href="/testcourse">
	    <div class="step-progress-indicator complete">
	      <span class="step-progress-indicator-icon complete"></span>
	    </div>

	    <div class="step-info">
	      <h3 class="list-group-item-heading step-title">
	        1. Subject: First lesson
	      </h3>
	      <p class="list-group-item-text step-description">Description of first lesson</p>
	    </div>
	</a>
</div>

app/views/pages/home.html.erb
<div class="masthead">
  <div class="container" style="padding:200px;">
    <div class="row">
      <div class="col-md-12">
        <h1>Don't waste your time locked away learning to code</h1>
        <p>Learn the basic tools you need as an MBA to start a tech company</p>
        <%= link_to "Enroll today for $20", new_user_registration_path(:plan => 'VIP'), class: "btn btn-primary btn-lg btn-embossed" %>
      </div>
    </div>
  </div>
</div>
  
<!-- use this to make up for weird spacing -->
  <div class="right ribbon-corner-holder" >

  </div>

<!-- features section -->
<section class="features" style="border: 5px bold solid;" >
  <div class="container" style="padding:150px;" >
    <div class="row center">


      <div class="col-sm-4">
        <span class="glyphicon glyphicon-cog" style="font-size:80px"></span>
        <h4 class="feature">Step-by-step videos</h3>
        <p>Tech made simple, with the MBA skillset in mind</p>
      </div>

      <div class="col-sm-4">
        <span class="glyphicon glyphicon-wrench" style="font-size:80px"></span>
        <h4 class="feature">Build practical skills</h3>
        <p>Every month we will release a crazy amount of content that will help you bring real value to a startup or start your own company</p>
        <p></p>
      </div>

      <div class="col-sm-4">
        <span class="glyphicon glyphicon-user" style="font-size:80px"></span>
        <h4 class="feature">We're one of you</h3>
        <p>And we're always here to provide you more information and and answer your questions</p>
      </div>
    </div>
  </div>
</section>

<section class="testimonials" >
  <div class="container" style="padding:100px;" >
    <div class="media">
      <a class="pull-left" href="#">
      <img class="media-object" src="#" alt="#">
    </a>
      <div class="media-body">
        <h4 class="media-heading">Kristin Johnson, Columbia Business School</h4>
        <p>Elliot and Kenny are amazing teachers and incredibly knowledgeable about the practicalities of tech.  I've been doing lots of strategy in school, but these courses have rounded out my skills so that I feel truly valuable at the startup I'm interning with.</p><br><br><br>
      </div>
    </div>

    <div class="media">
      <a class="pull-right" href="#">
      <img class="media-object" src="#" alt="#">
    </a>
      <div class="media-body">
        <h4 class="media-heading">Marky Marks, Harvard Business School</h4>
        <p>Amazing amazing amazing Amazing amazing amazingAmazing amazing amazingAmazing amazing amazingAmazing amazing amazingAmazing amazing amazingAmazing amazing amazingAmazing amazing amazingAmazing amazing amazingAmazing amazing amazing</p><br><br><br>
      </div>
    </div>

    <div class="media">
      <a class="pull-left" href="#">
      <img class="media-object" src="#" alt="#">
    </a>
      <div class="media-body">
        <h4 class="media-heading">Thsi guy, Booth School of Business</h4>
        <p>Fantastic FantasticFantasticFantasticFantasticFantasticFantasticFantasticFantasticFantasticFantasticFantasticFantasticFantasticFantasticFantasticFantasticFantasticFantastic</p>
      </div>
    </div>

  </div>
</section>

app/views/pages/testcourse.html.erb
<div class="container">

	<%= link_to "Back to courses", courses_path, class: "btn btn-danger btn-lg btn-embossed" %>

	<h1>How to open/edit an HTML file</h1>
	<iframe width="1140" height="641" src="//www.youtube.com/embed/15BvztvpSbY?rel=0" frameborder="0" allowfullscreen></iframe>

	<div class="text-explanation" style="padding: 50px 0 50px 0;">
		<div class="panel panel-default">
	  		<div class="panel-heading">
	  			<p>Why open an HTML file</p>
	  		</div>
	  		<div class="panel-body">
	    		<p>You make want to open an HMTL file to look at the actual code.</p>
	    		<p>You cannot do this in Microsoft Word or other such tools.  You must do it in a text editor</p>
	 		 </div>
		</div>

		<div class="panel panel-default">
	  		<div class="panel-heading">
	  			<p>How to open an HTML file</p>
	  		</div>
	  		<div class="panel-body">
	    		<p>First, click this button, then do this</p>
	    		<p>Do this then this then this</p>
	    		<p>More examples are available</p>
	 		 </div>
		</div>
	</div>

</div>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<h3>Users</h3>
	<div class="span8">
	<table class="table table-condensed">
	    <thead>
	      <tr>
	          <th>Username</th>
	          <th>Email</th>
	          <th>Registered</th>
	          <th>Role</th>
	          <th></th>
	          <th></th>
	      </tr>
	  </thead>
	  <tbody>
	  <% @users.each do |user| %>
	    <tr>
	        <td><%= link_to user.name, user %></td>
	        <td><%= user.email %></td>
	        <td><%= user.created_at.to_date %></td>
	        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
	        <td>
	          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
	          <%= render user %>
	        </td>
	        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
	    </tr>
	  <% end %>
	  </tbody>
	</table>
	</div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>